Repository TeskaLabs/cysimdjson, pull requests merged in 2023-07, with the labels that each got.

#42 fix: memory leak from keys (issue 41)
  cysimdjson/cysimdjson.pyx
Labels: bug

#44 Upgrade to simdjson 3.2.1
  cysimdjson/cysimdjson.pyx
  cysimdjson/jsoninter.h
  cysimdjson/simdjson/LICENSE
  cysimdjson/simdjson/README.md
  cysimdjson/simdjson/simdjson.cpp
  cysimdjson/simdjson/simdjson.h
  setup.py
Labels: bug, enhancement

#46 Add a C API capability to export parsed JSON as a string.
  cysimdjson/cysimdjsonc.cpp
  cysimdjson/cysimdjsonc.h
  test/test_capi/__init__.py
Labels: enhancement
